export const FETCH_IMAGES = 'FETCH_IMAGES';
export const FETCH_IMAGES_ERRORS = 'FETCH_IMAGES_ERRORS';
export const FETCH_AUDIO = 'FETCH_AUDIO';
export const FETCH_AUDIO_ERRORS = 'FETCH_AUDIO_ERRORS';
